/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-02-09 15:39:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1675955957757L));
    _jspx_dependants.put("jar:file:/C:/su_cho/workspace/bookae/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookAe/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/su_cho/workspace/bookae/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookAe/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"author\" content=\"sujin\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"resources/images/그림2.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/index.css\">\r\n");
      out.write("    <script src=\"resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/index.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/common.js\"></script>\r\n");
      out.write("	<title>북愛 - 메인 페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--건너뛰기 링크 시작-->\r\n");
      out.write("    <a id=\"skipNav\" href=\"mainContents\">본문 바로가기</a>\r\n");
      out.write("    <!--건너뛰기 링크 종료-->\r\n");
      out.write("    \r\n");
      out.write("    <!--#wrapper 시작-->\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--mainContents 시작-->\r\n");
      out.write("        <div id=\"contentsArea\">\r\n");
      out.write("            <!--이미지 배너-->\r\n");
      out.write("            <div class=\"overflowImage\">\r\n");
      out.write("                <img id=\"whasalL\" src=\"resources/images/whasal1.png\" alt=\"ImageBannerPrev\">\r\n");
      out.write("                <img id=\"whasalR\" src=\"resources/images/whasal2.png\" alt=\"ImageBannerNext\">\r\n");
      out.write("                <div class=\"imageBanner\">\r\n");
      out.write("                    <h2 class=\"hidden\">이미지 배너</h2>\r\n");
      out.write("                    <img src=\"resources/images/banner1.png\" alt=\"banner1\">\r\n");
      out.write("                    <img src=\"resources/images/banner2.png\" alt=\"banner2\">\r\n");
      out.write("                    <img src=\"resources/images/banner3.png\" alt=\"banner3\">\r\n");
      out.write("                    <img src=\"resources/images/banner4.png\" alt=\"banner4\">\r\n");
      out.write("                    <img class=\"page1\" src=\"resources/images/banner5.png\" alt=\"banner5\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--베스트셀러-->\r\n");
      out.write("            <div class=\"bestSellerBanner\">\r\n");
      out.write("                <section id=\"BSday\">\r\n");
      out.write("                    <h3><a class=\"btnDay\" href=\"#BSday\" onclick=\"return false\">오늘의</a></h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"BS-title\">베스트 셀러</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_1\">1</p>\r\n");
      out.write("                                <img src=\"resources/images/day1.jpg\" alt=\"1등, 피라네시\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">피라네시</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">수재나 클라크</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_2\">2</p>\r\n");
      out.write("                                <img src=\"resources/images/day2.jpg\" alt=\"2등, 스토아적 삶의 권유\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">스토아적 삶의 권유</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">마르코스 바스케스</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_3\">3</p>\r\n");
      out.write("                                <img src=\"resources/images/day3.jpg\" alt=\"3등, 음식을 처방해 드립니다\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">음식을 처방해 드립니다</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">리나 네르트뷔 아우렐</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">4</p>\r\n");
      out.write("                                <img src=\"resources/images/day4week1month4.jpg\" alt=\"4등, 기특한 나\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">기특한 나</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">천선란</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">5</p>\r\n");
      out.write("                                <img src=\"resources/images/day5week2.jpg\" alt=\"5등, 시간을 찾아드립니다\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">시간을 찾아드립니다</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">애슐리 윌런스</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"#\" class=\"more\" title=\"오늘의 베스트셀러 더보기\">더보기</a>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section id=\"BSweek\">\r\n");
      out.write("                    <h3><a class=\"btnWeek\" href=\"#BSweek\" onclick=\"return false\">이번주의</a></h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"BS-title\">베스트 셀러</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_1\">1</p>\r\n");
      out.write("                                <img src=\"resources/images/day4week1month4.jpg\" alt=\"1등, 기특한 나\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">기특한 나</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">천선란</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_2\">2</p>\r\n");
      out.write("                                <img src=\"resources/images/day5week2.jpg\" alt=\"2등, 시간을 찾아드립니다\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">시간을 찾아드립니다</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">애슐리 윌런스</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_3\">3</p>\r\n");
      out.write("                                <img src=\"resources/images/week3.jpg\" alt=\"3등, 150년 하버드 글쓰기 비법\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">150년 하버드 글쓰기 비법</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">송숙희</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">4</p>\r\n");
      out.write("                                <img src=\"resources/images/week4month3.jpg\" alt=\"4등, 심리 읽어드립니다\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">심리 읽어드립니다</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">김경일</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">5</p>\r\n");
      out.write("                                <img src=\"resources/images/week5month1.jpg\" alt=\"5등, 나는 왜 혼자가 편할까?\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">나는 왜 혼자가 편할까?</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">오카다 다카시</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"#\" class=\"more\" title=\"이번주의 베스트셀러 더보기\">더보기</a>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section id=\"BSmonth\">\r\n");
      out.write("                    <h3><a class=\"btnMonth\" href=\"#BSmonth\" onclick=\"return false\">이번달의</a></h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li class=\"BS-title\">베스트 셀러</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_1\">1</p>\r\n");
      out.write("                                <img src=\"resources/images/week5month1.jpg\" alt=\"1등, 나는 왜 혼자가 편할까?\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">나는 왜 혼자가 편할까?</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">오카다 다카시</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_2\">2</p>\r\n");
      out.write("                                <img src=\"resources/images/month2.jpg\" alt=\"2등, 마음의 법칙\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">마음의 법칙</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">폴커 키츠</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <p class=\"rank_3\">3</p>\r\n");
      out.write("                                <img src=\"resources/images/week4month3.jpg\" alt=\"3등, 심리 읽어드립니다\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">심리 읽어드립니다</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">김경일</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">4</p>\r\n");
      out.write("                                <img src=\"resources/images/day4week1month4.jpg\" alt=\"4등, 기특한 나\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">기특한 나</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">천선란</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" class=\"etc\">\r\n");
      out.write("                                <p class=\"rank\">5</p>\r\n");
      out.write("                                <img src=\"resources/images/month5.jpg\" alt=\"5등, 편애하는 문장들\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"plus\">\r\n");
      out.write("                                        <div></div>\r\n");
      out.write("                                        <p>보러가기</p>\r\n");
      out.write("                                        <span>&gt;</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"bookName\">편애하는 문장들</p>\r\n");
      out.write("                                <p class=\"bookAuthor\">이유미</p>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <a href=\"#\" class=\"more\" title=\"이번달의 베스트셀러 더보기\">더보기</a>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--매거진-->\r\n");
      out.write("            <div id=\"magazineBanner\">\r\n");
      out.write("                <h2>매거진</h2>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"#\"><img src=\"resources/images/magazine1.jpg\" alt=\"작가 이미예\"></a>\r\n");
      out.write("                            <span>&lt;인터뷰&gt;</span>\r\n");
      out.write("                            <h3><a href=\"#\">&lt;달러구트 꿈 백화점&gt;<br>작가 이미예 인터뷰</a></h3>\r\n");
      out.write("                            <p class=\"naeyoung\"><a href=\"#\">그는 이름만 대면 누구나 아는 기업의 직원이었다. 부유하지는 않지만 부족하지 않은 삶을 일구었다. 그랬던 그가 큰일을 냈다. 평화롭고 안정적인 직장 생활에 마침표를 찍기로 결심한 것이다. 그 길로 회사에 사표를 제출했다. 그리고 2년 뒤, 그는 베스트셀러 작가가 되었다.<br>이미예는 독자가 직접 발굴한 작가라는 점에서 특별하다. &lt;달러구트 꿈 백화점&gt;은 출판사를 통해 정식 출간되기 전에 작가가 크라우드 펀딩으로 독립 출판을 먼저 한 책이었다. 이 펀딩은 목표 대비 1,800%를 초과 달성하며 큰 성공을 거두었다. 그의 글을 알아본 독자들은 읽고 나면 기분이 좋아지는 글이라는 호평을 쏟아냈다. 이후 그는 출판사와 정식으로 전자책을 출간하여 리디북스에서 1위를 달성하였고 곧이어 낸 종이책은 11만 부를 판매하여 베스트셀러에 오른다.</a></p>\r\n");
      out.write("                            <p class=\"plus\">p</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"#\"><img src=\"resources/images/magazine2.png\" alt=\"책 읽는 서울 광장\"></a>\r\n");
      out.write("                            <span>&lt;행사&gt;</span>\r\n");
      out.write("                            <h3><a href=\"#\">&#39;책 읽는 서울광장&#39;<br>북토크 행사에 참여해보다</a></h3>\r\n");
      out.write("                            <p class=\"naeyoung\"><a href=\"#\">서울시는 6월 한 달 동안 '책 읽는 서울광장'에서 인기 문학작가들이 참여하는 북토크 프로그램 '풀밭 위의 문학 산책'을 운영한다고 밝혔습니다. '풀밭 위의 문학 산책'은 매주 금요일 낮 12시, 토요일 오전 11시에 서울광장 동쪽에서 진행됩니다.<br>첫째 주에는 SF소설 '나인'을 주제로 작가 천선란과 작가이자 작곡가 겸 유튜버인 김겨울이 참여하고, '7년의 밤' 정유정 작가와 오은 시인이 함께하는 토크 콘서트가 열립니다.프로그램 참여를 원하는 시민은 서울도서관 홈페이지(lib.seoul.go.kr)에서 신청하면 됩니다.</a></p>\r\n");
      out.write("                            <p class=\"plus\">p</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"#\"><img src=\"resources/images/magazine3.jpg\" alt=\"서울 국제도서전 포스터\"></a>\r\n");
      out.write("                            <span>&lt;뉴스&gt;</span>\r\n");
      out.write("                            <h3><a href=\"#\">‘서울국제도서전’<br>3년 만에 정상 개최</a></h3>\r\n");
      out.write("                            <p class=\"naeyoung\"><a href=\"#\">국내 최대 규모의 책 축제인 ‘서울국제도서전’이 내달 1일부터 5일까지 서울 코엑스에서 열린다. 이번 행사는 지난 2년간 코로나19로 축소 개최된 후 3년만에 정상적으로 열리는 행사로, 그 의미가 더욱 크다. 문화체육관광부는 30일 대한출판문화협회와 함께 제28회 서울국제도서전을 개최한다고 밝혔다. 올해 주빈국은 한국과 수교 60주년을 맞이한 콜롬비아다. 양국이 수교 60주년을 기념해 상대국 도서전의 주빈국으로 참가하기로 지난해 8월 합의함에 따라 한국은 지난 달 ‘보고타국제도서전’에 주빈국으로 참가한 바 있다. 올해 도서전의 주제는 ‘반걸음(One Small Step)’이다. 이는 세상을 바꾼 거대한 변화의 시작점은 기존의 고정관념을 깨고 용기 있게 나아간 ‘반걸음’이었다는 의미를 담고 있다.</a></p>\r\n");
      out.write("                            <p class=\"plus\">p</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <a href=\"#\" class=\"more\" title=\"매거진 더보기\">더보기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--북애의 선택, 셀럽의 선택-->\r\n");
      out.write("            <div id=\"choice\">\r\n");
      out.write("                <section class=\"bookaeChoice\">\r\n");
      out.write("                    <h2>북애의 선택</h2>\r\n");
      out.write("                    <img src=\"resources/images/choice1.jpg\" alt=\"벚꽃지는 계절에 그대를 그리워하네 표지\">\r\n");
      out.write("                    <div class=\"naeyong\">\r\n");
      out.write("                        <div class=\"naeCenter\">\r\n");
      out.write("                            <h3>『벚꽃지는 계절에 그대를 그리워하네』</h3>\r\n");
      out.write("                            <p class=\"author\">우타노 쇼고</p>\r\n");
      out.write("                            <p class=\"quotes\"><span>\"</span>꽃이 떨어진 후에도 벚나무는 살아 있어.<span>\"</span></p>\r\n");
      out.write("                            <p class=\"recommend\">벚꽃이 지고 난 뒤 시작되는 대반전의 드라마<br>어떤 트릭인지 알아도 모두가 속고 마는 반전!</p>\r\n");
      out.write("                            <a class=\"more\" href=\"#\">-자세히 보러가기-</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"celebrityChoice\">\r\n");
      out.write("                    <h2>셀럽의 선택</h2>\r\n");
      out.write("                    <p class=\"celebrityRecommend\"><span>키커스</span>가 추천하는 최고의 책</p>\r\n");
      out.write("                    <img src=\"resources/images/choice2.jpg\" alt=\"팍스 표지\">\r\n");
      out.write("                    <div class=\"naeyong\">\r\n");
      out.write("                        <div class=\"naeCenter\">\r\n");
      out.write("                            <h3>『팍스』</h3>\r\n");
      out.write("                            <p class=\"author\">사라 페니패커</p>\r\n");
      out.write("                            <p class=\"quotes\"><span>\"</span>인간 친구가 나를 찾으러 올 거예요.<span>\"</span></p>\r\n");
      out.write("                            <p class=\"recommend\">여우와 소년, 작고 평범한 존재가 보여준 강렬한 우정<br>\r\n");
      out.write("                                인간과 동물이 만들어 낸 위대한 가치</p>\r\n");
      out.write("                            <a class=\"more\" href=\"#\">-자세히 보러가기-</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--mainContents 종료-->\r\n");
      out.write("\r\n");
      out.write("        <!--footer 시작-->\r\n");
      out.write("        <footer id=\"footer\">\r\n");
      out.write("            <div id=\"footerInner\">\r\n");
      out.write("                <section class=\"guide\">\r\n");
      out.write("                    <h2 class=\"hidden\">사이트 이용안내</h2>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">회사 소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이용 약관</a></li>\r\n");
      out.write("                        <li><a href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("                        <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("                <address>\r\n");
      out.write("                    <span>㈜북애</span>\r\n");
      out.write("                    <span>대표이사: 조수진</span>\r\n");
      out.write("                    <span>서울특별시 종로구 미려빌딩6층</span>\r\n");
      out.write("                    <span>전화: 02-666-1717</span>\r\n");
      out.write("                    <span>E-MAIL: <a href=\"mailto:bookAe@bookAe.com\">bookAe@bookAe.com</a></span>\r\n");
      out.write("                </address>\r\n");
      out.write("                <p class=\"copyright\">Copyright since &copy; 2022 by BookAe CORPORATION ALL RIGHTS RESERVED.</p>\r\n");
      out.write("                <p class=\"relCite\">\r\n");
      out.write("                    <select id='cite' name=\"relatedCite\" onchange=\"citeIdong();\">\r\n");
      out.write("                        <option value=\"no\">관련 사이트</option>\r\n");
      out.write("                        <option value=\"kyobo\">교보문고</option>\r\n");
      out.write("                        <option value=\"yes24\">yes24</option>\r\n");
      out.write("                        <option value=\"aladin\">알라딘</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <a class=\"btncite\">이동</a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!--footer 종료-->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--#wrapper 종료-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/index.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
