/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-03-08 15:55:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1675955957757L));
    _jspx_dependants.put("jar:file:/C:/su_cho/workspace/bookae/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookAe/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/su_cho/workspace/bookae/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookAe/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"author\" content=\"sujin\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"resources/images/그림2.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/normalize.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"resources/css/index.css\">\r\n");
      out.write("    <script src=\"resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/index.js\"></script>\r\n");
      out.write("    <script src=\"resources/js/common.js\"></script>\r\n");
      out.write("	<title>북愛 - 메인 페이지</title>\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		#like_btn{\r\n");
      out.write("			width: 120px;\r\n");
      out.write("		    height: 65px;\r\n");
      out.write("		    font-size: 0.9em;\r\n");
      out.write("		    border-radius: 5%;\r\n");
      out.write("		    background-color: #fff;\r\n");
      out.write("		}\r\n");
      out.write("		.unlike{\r\n");
      out.write("		    border: 3px solid #ccc;\r\n");
      out.write("		}\r\n");
      out.write("		.unlike:hover{\r\n");
      out.write("			border: 3px solid #ffb7b7;\r\n");
      out.write("		}\r\n");
      out.write("		.like{\r\n");
      out.write("			border: 3px solid #ffb7b7;\r\n");
      out.write("		}\r\n");
      out.write("		#heart{\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("		    width: 23px;\r\n");
      out.write("		    text-indent: 23px;\r\n");
      out.write("		    overflow: hidden;\r\n");
      out.write("		    white-space: nowrap;\r\n");
      out.write("		}\r\n");
      out.write("		.unlike #heart::before{\r\n");
      out.write("			position: relative;\r\n");
      out.write("		    left: -20px;\r\n");
      out.write("		    top: 3px;\r\n");
      out.write("		    content: \"♡\";\r\n");
      out.write("			color: rgb(245, 27, 27);\r\n");
      out.write("		}\r\n");
      out.write("		.unlike:hover #heart::before{\r\n");
      out.write("			content: \"♥\";\r\n");
      out.write("		}\r\n");
      out.write("		.like #heart::before{\r\n");
      out.write("			position: relative;\r\n");
      out.write("		    left: -20px;\r\n");
      out.write("		    top: 3px;\r\n");
      out.write("		    content: \"♥\";\r\n");
      out.write("			color: rgb(245, 27, 27);\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	    function find() {\r\n");
      out.write("	    	var name=document.getElementById(\"name\").value;\r\n");
      out.write("	    	if(!name){\r\n");
      out.write("	    		alert(\"전화번호를 입력하삼\");\r\n");
      out.write("	    		return;\r\n");
      out.write("	    	}\r\n");
      out.write("	    	\r\n");
      out.write("	    	var data={\"name\":name};\r\n");
      out.write("	    	\r\n");
      out.write("	    	$.ajax({\r\n");
      out.write("	    		type:\"post\",\r\n");
      out.write("	    		dataType:\"json\",\r\n");
      out.write("	    		data: data,\r\n");
      out.write("	    		url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/test.do\",\r\n");
      out.write("	    		success:function(result){\r\n");
      out.write("	    			$(\"#place\").html(\"\");\r\n");
      out.write("	    			$(\"#place\").append(\r\n");
      out.write("   						\"<h2>고객님의 전화번호는 \"+result['tel']+\"입니다.</h2>\"\r\n");
      out.write("   					);\r\n");
      out.write("	    		}\r\n");
      out.write("	    	})\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    function like() {\r\n");
      out.write("	    	var id=\"tnwls356\";\r\n");
      out.write("	    	var board_num=10;\r\n");
      out.write("	    	var board_like=2;\r\n");
      out.write("	    	\r\n");
      out.write("	    	var data={\"id\" : id, \"board_num\":board_num};\r\n");
      out.write("	    	\r\n");
      out.write("	    		$.ajax({\r\n");
      out.write("	    			type:\"post\",\r\n");
      out.write("	    			dataType:\"json\",\r\n");
      out.write("	    			data: data,\r\n");
      out.write("	    			url:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/addLike.do',\r\n");
      out.write("    				success:function(data){\r\n");
      out.write("    					alert('좋아요 성공!');\r\n");
      out.write("    					$(\"#like_btn\").attr('class','like');\r\n");
      out.write("    					$(\"#board_like\").text(board_like+1);\r\n");
      out.write("    				}\r\n");
      out.write("	    		})\r\n");
      out.write("	    	\r\n");
      out.write("	    }\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <input type=\"text\" id=\"name\">\r\n");
      out.write("    <input type=\"button\" value=\"찾기\" onclick=\"find()\">\r\n");
      out.write("    <div id=\"place\"></div>\r\n");
      out.write("    \r\n");
      out.write("    <button id=\"like_btn\" class=\"unlike\" onclick=\"like()\"><span id=\"heart\">추천수</span><br><span id=\"board_like\">2</span></button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/index.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
